version: '3.7'

services:
  brouter-web:
    build: ../brouter-web/
    ports:
        - "8083:80"
    volumes:
        - ../brouter/data/profiles:/usr/share/nginx/html/profiles
    depends_on:
      - brouter-app
  brouter-app:
    build: ../brouter/
    ports:
        - "17776:17777"
    volumes:
        - ../brouter/data/profiles:/data/profiles
        - ../brouter/data/segments:/data/segments
        - ../brouter/data/customprofiles:/data/customprofiles
    environment:
        - REQUEST_TIMEOUT=300
        - JAVA_OPTS=-Xmx512M -Xms512M -Xmn16M -XX:+PrintCommandLineFlags
        - MAX_THREADS=4
  tiles:
    build: ../openstreetmap-tile-server-cyclosm/
    command: run
    volumes:
      - openstreetmap-cyclosm-data-upd:/var/lib/postgresql/12/main
    ports:
      - 8081:80
    environment:
      - UPDATES=enabled
  pois:
    build: ../tile-server-pois/
    command: run
    volumes:
      - openstreetmap-cyclosm-data-poi:/var/lib/postgresql/12/main
    ports:
      - 8084:80
    environment:
      - UPDATES=enabled

volumes:
  openstreetmap-cyclosm-data-upd:
    external: true
  openstreetmap-cyclosm-data-poi:
    external: true
