version: '3.7'

services:
  brouter-web:
    build: ../brouter-web/
    ports:
        - "8083:80"
    volumes:
        - ../brouter/data/profiles:/usr/share/nginx/html/profiles
    depends_on:
      - brouter-app
  brouter-app:
    build: ../brouter/
    ports:
        - "17776:17777"
    volumes:
        - ../brouter/data/profiles:/data/profiles
        - ../brouter/data/segments:/data/segments
        - ../brouter/data/customprofiles:/data/customprofiles
    environment:
        - REQUEST_TIMEOUT=300
        - JAVA_OPTS=-Xmx512M -Xms512M -Xmn16M -XX:+PrintCommandLineFlags
        - MAX_THREADS=4
  tiles:
    build:
      context: ../gravel-tile-server/
      args:
        - STYLEREPO=https://github.com/cxberlin/gravel-cartocss-style.git
        - STYLECOMMIT=3310be06f08ab362eade0d650c3bebae42c478e2
    command: run
    image: cxberlin/tileserver
    volumes:
      - openstreetmap-cyclosm-data-eu-nov20:/var/lib/postgresql/12/main
    ports:
      - 8081:80
    environment:
      - UPDATES=enabled
  pois:
    build:
      context: ../gravel-tile-server/
      args:
        - STYLEREPO=https://github.com/stefankeidel/poi-cartocss-style.git
        - STYLECOMMIT=1cc042f00c64f4e15e09018688343198f505a9f9
    command: run
    volumes:
      - openstreetmap-cyclosm-data-poi:/var/lib/postgresql/12/main
    ports:
      - 8084:80
    environment:
      - UPDATES=enabled
  osm-import:
    image: cxberlin/tileserver
    depends_on:
      - tiles
    volumes:
      - openstreetmap-cyclosm-data-eu-feb21:/var/lib/postgresql/12/main
    command: import
    environment:
      - THREADS=4
      - UPDATES=enabled
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe-latest.osm.pbf
      - DOWNLOAD_POLY=https://download.geofabrik.de/europe.poly
    deploy:
      resources:
        limits:
          memory: 6G

volumes:
  openstreetmap-cyclosm-data-eu-nov20:
    external: true
  openstreetmap-cyclosm-data-eu-feb21:
    external: true
  openstreetmap-cyclosm-data-poi:
    external: true
