version: '3.7'

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - proxy
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  redirect:
    image: adamkdean/redirect
    environment:
      - VIRTUAL_HOST=keidel.me
      - LETSENCRYPT_HOST=keidel.me
      - REDIRECT_LOCATION=http://www.keidel.me
      - REDIRECT_STATUS_CODE=301
      - PRESERVE_URL=true

  brouter-web:
    build: ../brouter-web/
    ports:
        - "8083:80"
    volumes:
        - ../brouter/data/profiles:/usr/share/nginx/html/profiles
        - /etc/localtime:/etc/localtime:ro
    depends_on:
      - brouter-app
      - letsencrypt
      - proxy
    environment:
      - VIRTUAL_HOST=routing.cxberlin.net
      - LETSENCRYPT_HOST=routing.cxberlin.net
      - LETSENCRYPT_EMAIL=accounts@keidel.me
  brouter-app:
    build: ../brouter/
    ports:
        - "17776:17777"
    depends_on:
      - letsencrypt
      - proxy
    volumes:
        - ../brouter/data/profiles:/data/profiles
        - ../brouter/data/segments:/data/segments
        - ../brouter/data/customprofiles:/data/customprofiles
        - /etc/localtime:/etc/localtime:ro
    environment:
        - REQUEST_TIMEOUT=300
        - JAVA_OPTS=-Xmx512M -Xms512M -Xmn16M -XX:+PrintCommandLineFlags
        - MAX_THREADS=4
        - VIRTUAL_HOST=brouter.cxberlin.net
        - LETSENCRYPT_HOST=brouter.cxberlin.net
        - LETSENCRYPT_EMAIL=accounts@keidel.me
  tiles:
    build:
      context: ../gravel-tile-server/
      args:
        - STYLEREPO=https://github.com/cxberlin/gravel-cartocss-style.git
        - STYLECOMMIT=cf4be2118aed3cd390a886fe1bf2344ee79106e2
    command: run
    depends_on:
      - letsencrypt
      - proxy
    image: cxberlin/tileserver
    volumes:
      - osm-data-2023-11-01:/var/lib/postgresql/12/main
    ports:
      - 8081:80
    environment:
      - UPDATES=enabled
      - VIRTUAL_HOST=tiles.cxberlin.net
      - LETSENCRYPT_HOST=tiles.cxberlin.net
      - LETSENCRYPT_EMAIL=accounts@keidel.me
  osm-import:
    image: mhajder/openstreetmap-tile-server-cyclosm
    volumes:
      - osm-data-2023-11-01:/var/lib/postgresql/12/main
    command: import
    environment:
      - THREADS=2
      - UPDATES=enabled
      - DOWNLOAD_PBF=https://download.geofabrik.de/europe-latest.osm.pbf
      - DOWNLOAD_POLY=https://download.geofabrik.de/europe.poly
      - OSM2PGSQL_EXTRA_ARGS=-C 4096

  keidel-me:
    image: nginx
    depends_on:
      - letsencrypt
      - proxy
    volumes:
      - /home/stefan/keidel-me/services/web/static/keidel-me:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=www.keidel.me
      - LETSENCRYPT_HOST=www.keidel.me
      - LETSENCRYPT_EMAIL=accounts@keidel.me


# Stefan Nextcloud
  nc-stefan-db:
    image: postgres:13
    volumes:
      - nc-stefan-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETWORK_ACCESS=internal
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=unicorn
      - POSTGRES_DB=nextcloud
    restart: unless-stopped

  nc-stefan-app:
    image: nextcloud:27
    depends_on:
      - letsencrypt
      - proxy
      - nc-stefan-db
    volumes:
      - nc-stefan-app:/var/www/html
      - ./nc-stefan/config:/var/www/html/config
      - ./nc-stefan/custom_apps:/var/www/html/custom_apps
      - ./nc-stefan/data:/var/www/html/data
      - ./nc-stefan/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERWRITEPROTOCOL=https
      - PHP_UPLOAD_LIMIT=16384M
      - VIRTUAL_HOST=cloud.keidel.me
      - LETSENCRYPT_HOST=cloud.keidel.me
      - LETSENCRYPT_EMAIL=accounts@keidel.me
    restart: unless-stopped

# Grevet Nextcloud
  nc-grevet-db:
    image: postgres:13
    volumes:
      - nc-grevet-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETWORK_ACCESS=internal
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=unicorn
      - POSTGRES_DB=nextcloud
    restart: unless-stopped

  nc-grevet-app:
    image: nextcloud:25
    depends_on:
      - letsencrypt
      - proxy
      - nc-grevet-db
    volumes:
      - nc-grevet-app:/var/www/html
      - ./nc-grevet/config:/var/www/html/config
      - ./nc-grevet/custom_apps:/var/www/html/custom_apps
      - ./nc-grevet/data:/var/www/html/data
      - ./nc-grevet/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERWRITEPROTOCOL=https
      - PHP_UPLOAD_LIMIT=8192M
      - VIRTUAL_HOST=nextcloud.grevet.de
      - LETSENCRYPT_HOST=nextcloud.grevet.de
      - LETSENCRYPT_EMAIL=accounts@keidel.me
    restart: unless-stopped


volumes:
  nc-stefan-app:
    external: true
  nc-stefan-db:
    external: true
  nc-grevet-app:
    external: true
  nc-grevet-db:
    external: true
  osm-data-2023-11-01:
    external: true
